version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  node: circleci/node@6.3.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve
  preview-terraform:
    description: "Preview terraform configuration changes"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
            terraform plan
          name: preview terraform
  deploy-lambda:
    description: "Deploys via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - node/install
      - run:
          name: Build lambda
          command: |
            cd ./FinanceChargesListener/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./FinanceChargesListener/
            npx --yes serverless deploy --stage <<parameters.stage>> --conceal

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build finance-charges-listener-test
      - run:
          name: Run tests
          command: docker-compose run finance-charges-listener-test
  assume-role-development:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DEVELOPMENT
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  terraform-init-and-apply-to-development:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "development"
  terraform-init-and-apply-to-staging:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "staging"
  terraform-init-and-apply-to-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "production"
  preview-development-terraform:
    executor: docker-terraform
    steps:
      - preview-terraform:
          environment: "development"
  preview-staging-terraform:
    executor: docker-terraform
    steps:
      - preview-terraform:
          environment: "staging"
  preview-production-terraform:
    executor: docker-terraform
    steps:
      - preview-terraform:
          environment: "production"
  deploy-to-development:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "development"
  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "staging"
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

workflows:
  feature:
    jobs:
      - check-code-formatting:
          context: api-nuget-token-context
          filters:
            branches:
              ignore:
                - development
                - master
      - build-and-test:
          context: 
            - api-nuget-token-context
            - SonarCloud
          filters:
            branches:
              ignore:
                - development
                - master
      - assume-role-development:
          context: api-assume-role-housing-development-context
          filters:
            branches:
              ignore:
                - development
                - master
      - preview-development-terraform:
          requires:
            - assume-role-development
          filters:
            branches:
              ignore:
                - development
                - master
      - assume-role-staging:
          context: api-assume-role-housing-staging-context
          filters:
            branches:
              ignore:
                - development
                - master
      - preview-staging-terraform:
          requires:
            - assume-role-staging
          filters:
            branches:
              ignore:
                - development
                - master
      - assume-role-production:
          context: api-assume-role-housing-production-context
          filters:
            branches:
              ignore:
                - development
                - master
      - preview-production-terraform:
          requires:
            - assume-role-production
          filters:
            branches:
              ignore:
                - development
                - master
  check-and-deploy-development:
    jobs:
      - check-code-formatting:
          context: api-nuget-token-context
          filters:
            branches:
              only: development
      - build-and-test:
          context:
            - api-nuget-token-context
            - SonarCloud
          filters:
            branches:
              only: development
      - assume-role-development:
          context: api-assume-role-housing-development-context
          requires:
            - check-code-formatting
            - build-and-test
          filters:
            branches:
              only: development
      - terraform-init-and-apply-to-development:
          requires:
            - assume-role-development
          filters:
            branches:
              only: development
      - deploy-to-development:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - terraform-init-and-apply-to-development
          filters:
            branches:
              only: development
  check-and-deploy-staging-and-production:
      jobs:
      - check-code-formatting:
          context: api-nuget-token-context
          filters:
            branches:
              only: master
      - build-and-test:
          context:
            - api-nuget-token-context
            - SonarCloud
          filters:
            branches:
              only: master
      - assume-role-staging:
          context: api-assume-role-housing-staging-context
          requires:
              - build-and-test
          filters:
             branches:
               only: master
      - terraform-init-and-apply-to-staging:
          requires:
            - assume-role-staging
          filters:
            branches:
              only: master
      - deploy-to-staging:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - terraform-init-and-apply-to-staging
          filters:
            branches:
              only: master
      - permit-production-terraform-release:
          type: approval
          requires:
            - deploy-to-staging
          filters:
            branches:
              only: master
      - assume-role-production:
          context: api-assume-role-housing-production-context
          requires:
              - permit-production-terraform-release
          filters:
             branches:
               only: master
      - terraform-init-and-apply-to-production:
          requires:
            - assume-role-production
          filters:
            branches:
              only: master
      - permit-production-release:
          type: approval
          requires:
            - deploy-to-staging
            - terraform-init-and-apply-to-production
          filters:
            branches:
              only: master
      - deploy-to-production:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - permit-production-release
            - terraform-init-and-apply-to-production
          filters:
            branches:
              only: master
